### ISSUE TITLE
model vs teacher/student_model in yaml

### ISSUE THREAD

**Issue by jsiloto** [yoshitomo-matsubara/hnd-ghnd-object-detectors#24]
Hello, 
I was able to reproduce your code with minor adjustments but I'm reporting the error in the current version. 
Also, if you could answer some questions that would be great
- Is the mimic_runner.py the trainer for distillation training? Could you provide an example?
- What is the ext_runner script for?

## Bug
input:
```
pipenv run python src/coco_runner.py --config config/hnd/faster_rcnn-backbone_resnet50-b3ch.yaml 
```
output:
```
...
Creating model
Traceback (most recent call last):
  File "src/coco_runner.py", line 135, in <module>
    main(parser.parse_args())
  File "src/coco_runner.py", line 117, in main
    model_config = config['model']
KeyError: 'model'
```

**Comment by yoshitomo-matsubara** [comment]
Hello @jsiloto 

Thank you for your interest in our work!
`src/coco_runner.py` is for training original models (from torchvision) and designed to work with config files under `config/org/`, so it's not a bug.

To use HND and GHND approaches, you'll need run `src/mimic_runner.py` with a config file under `config/hnd/` and `config/ghnd/`.

`src/ext_runner.py` is for training and testing a neural filter, designed to filter out images without any objects of interest at mobile device (and terminate the inference before offloading in practice) for reducing inference time. We applied the neural filter to our bottleneck-injected Keypoint R-CNN model.
For details, please refer to Section 5 in the paper (Note the arXiv version will be updated tomorrow).


I will update README with more example commands as soon as possible.

**Comment by jsiloto** [comment]
Hello!
Things are clearer now. Thanks for such a speedy response, and kudos for the code, it looks very well written overall.

**Comment by yoshitomo-matsubara** [comment]
Glad to hear that! I just updated README to resolve your concerns.
Hope our code and camera-ready paper (the updated one will be available on arXiv tomorrow) help your work.
